"""Add doc_type column

Revision ID: 5e8d7c6b9a2f
Revises: 842276fefcd4
Create Date: 2026-03-19 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8d7c6b9a2f'
down_revision: Union[str, None] = '842276fefcd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs_metadata', sa.Column('doc_type', sa.String(), nullable=False, server_default='prd'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs_metadata', 'doc_type')
    # ### end Alembic commands ###
