"""Initial migration

Revision ID: 842276fefcd4
Revises: 
Create Date: 2026-03-17 06:48:42.051614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842276fefcd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_metadata_id'), 'docs_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_docs_metadata_module'), 'docs_metadata', ['module'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('origin_content', sa.Text(), nullable=False),
    sa.Column('optimized_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_id'), 'review_tasks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('conflict_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_cards_id'), 'conflict_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflict_cards_id'), table_name='conflict_cards')
    op.drop_table('conflict_cards')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_review_tasks_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_docs_metadata_module'), table_name='docs_metadata')
    op.drop_index(op.f('ix_docs_metadata_id'), table_name='docs_metadata')
    op.drop_table('docs_metadata')
    # ### end Alembic commands ###
